### ISSUE TITLE
Crash 1.16.4

### ISSUE THREAD

**Issue by agentwolf88** [SaemonMoki/ExtendedAnimals#55]
https://paste.ee/p/dpKzu

**Comment by Coraline77447** [comment]
I have this same exact issue but instead of a ticking entity crash it was a TICKING WORLD CRASH that was caused by an enhanced pig!

Mine may be the same enhanced animal as your enhanced animal that caused your game to crash or not but when it was apparently spawning into my modded world right as that spawnevent was happening right when I was working on something in my dark forest village (Repurposed Structures mod btw) that murdered my world!!! 

Luckily enough that I've backed up my current modded survival world several hours before this unrepairable crash happened but... 

All of my progress from when I made that backup till the absolute fatal crash is gone and all for nothing....

Now I'll have to redo everything that I've done right up till that point on time when the ticking world crash happened.....

**Comment by SaemonMoki** [comment]
upcoming version fixes this
