### ISSUE TITLE
(1.16.4) Invisible animals

### ISSUE THREAD

**Issue by Melsraynebow** [SaemonMoki/ExtendedAnimals#59]
I am not using any mods that change the vanilla animals or a texture pack yet the only animal that will show up not invisible is a chicken, is there anyway to fix this? I can hear the animal noises and hear them walking but they have no texture at all. Thank you in advance!

**Comment by KrisSchier** [comment]
i have the same issue. this is also valid for cows and sheeps.

also the new animals are not spawning. when i use the summon command i get an error ; object cant be created.

**Comment by SaemonMoki** [comment]
Are you playing on a server?
Also can you confirm if they are the vanilla animals that are invisible, or our animals?

**Comment by KrisSchier** [comment]
Yes playing on dedicated server.the vanilla animals are invisible and the new animals are not able to spawn

**Comment by KrisSchier** [comment]
and gamemod was survival

**Comment by SaemonMoki** [comment]
That is correct, vanilla animals will not spawn. Only our animals will, which don't replace vanilla as they are separate. There is config if you wish to still spawn vanilla animals. Otherwise our own will spawn instead. In already existing chunks it will take time to repopulate given how minecraft spawns in existing chunks.
