### ISSUE TITLE
Feature Requests: disable custom chicken item, fix chicken item tags, drop rate multipliers, chicken egg spawning

### ISSUE THREAD

**Issue by Ikxale** [SaemonMoki/ExtendedAnimals#60]
i have four separate suggestions/requests/issues, and i figure i'll avoid clogging the issues page by combining them into one issue, in order of importance.

1: there should be a config to disable the custom chicken items from spawning. having it active both clutters up the game, and introduces needless incompatibility with other mods such as harvestcraft

2: another aspect of the issue with compatibility is that only about half the chicken items are tagged, as well

3: add a multiplier, or some other config for animals, to make it so that they give a more realistic amount of food, whether by setting parameters, or by giving a drop rate multiplier

4: make chickens reproduce naturally when they lay eggs, by having the eggs spawn chickens when they despawn, up to a maximum of X within a radius of Y blocks, to avoid it from getting too over populated.

**Comment by SaemonMoki** [comment]
1: The meat difference is to show the results of breeding for various sizes. Without it kinda defeats the purpose of our mod. However, you can craft our chicken meat into vanilla chicken meat for compatibility purposes.

2: This is entirely intentional. Tagging the small chicken meat as vanilla chicken meat, would mean that players could breed smaller more food efficient chickens, and then use the meat to count the same as a larger(vanilla). Therefore unbalancing the point of breeding.

4: Again, intentional. By reducing the drops for specific genetic compositions, and allowing a much higher ceiling cap for specifically bred production animals, we are better able to showcase the power of genetics and breeding for production. For example, you can selectively breed cows to be high on meat, in same cases getting more than 6+ pieces of meat for one cow if bred for it. Simply adding multiplier config to change this completely defeats the purpose of the mod.

4: We already have this in the works. In fact we have something better than that planned, chickens will be able to brood and gather eggs to sit on, and hatch them themselves over time.
